spring.application.name=usuario


spring.datasource.url=jdbc:mysql://localhost:3306/odontologia
spring.datasource.username=root
spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.datasource.driverClassName=com.mysql.jdbc.Driver

server.port=8085

secret=hT+9vN2h8wZs3ZEDZjB9Shu34f1dGr2bUjDcz3cEhR4=
spring.main.allow-bean-definition-overriding=true
